/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  CVOLUSDTFeesCalculator,
  CVOLUSDTFeesCalculatorInterface,
} from "../CVOLUSDTFeesCalculator";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
    signature:
      "0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0",
  },
  {
    inputs: [],
    name: "buyingPremiumFeeMaxPercent",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xdfc4d213",
  },
  {
    inputs: [],
    name: "buyingPremiumThreshold",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x3a087eb7",
  },
  {
    inputs: [],
    name: "closePositionFeeDecayPeriod",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xa4b22027",
  },
  {
    inputs: [],
    name: "closePositionFeePercent",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x66733a78",
  },
  {
    inputs: [],
    name: "closePositionMaxFeePercent",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xcdb3632a",
  },
  {
    inputs: [],
    name: "depositFeePercent",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xcc1252ae",
  },
  {
    inputs: [],
    name: "fundingFeeConstantRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x759dbcad",
  },
  {
    inputs: [],
    name: "maxTurbulenceFeePercentToTrim",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xc1176c80",
  },
  {
    inputs: [],
    name: "openPositionFeePercent",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xa2028d97",
  },
  {
    inputs: [],
    name: "openPositionLPFeePercent",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x76ebae42",
  },
  {
    inputs: [],
    name: "oracleHeartbeatPeriod",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xd7db90c1",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x8da5cb5b",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x715018a6",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0xf2fde38b",
  },
  {
    inputs: [],
    name: "turbulenceDeviationPercentage",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xf948b5eb",
  },
  {
    inputs: [],
    name: "turbulenceDeviationThresholdPercent",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x2cda452a",
  },
  {
    inputs: [],
    name: "turbulenceIndicatorPercent",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xf359b46f",
  },
  {
    inputs: [],
    name: "turbulenceStepPercent",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x406cab16",
  },
  {
    inputs: [],
    name: "turbulenceUpdator",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xdf0d2530",
  },
  {
    inputs: [],
    name: "withdrawFeePercent",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x495ef705",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_totalTime",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_newRounds",
        type: "uint256",
      },
      {
        internalType: "uint16",
        name: "_lastCVIValue",
        type: "uint16",
      },
      {
        internalType: "uint16",
        name: "_currCVIValue",
        type: "uint16",
      },
    ],
    name: "updateTurbulenceIndicatorPercent",
    outputs: [
      {
        internalType: "uint16",
        name: "updatedTurbulenceIndicatorPercent",
        type: "uint16",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x667dd316",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_newUpdator",
        type: "address",
      },
    ],
    name: "setTurbulenceUpdator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0xb2c0112e",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "_newDepositFeePercentage",
        type: "uint16",
      },
    ],
    name: "setDepositFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x0fe21264",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "_newWithdrawFeePercentage",
        type: "uint16",
      },
    ],
    name: "setWithdrawFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x322ce8f0",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "_newOpenPositionFeePercentage",
        type: "uint16",
      },
    ],
    name: "setOpenPositionFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x6266124e",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "_newClosePositionFeePercentage",
        type: "uint16",
      },
    ],
    name: "setClosePositionFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0xc11387d1",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "_newOpenPositionLPFeePercent",
        type: "uint16",
      },
    ],
    name: "setOpenPositionLPFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0xcb7241e5",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "_newClosePositionMaxFeePercentage",
        type: "uint16",
      },
    ],
    name: "setClosePositionMaxFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0xb0df807d",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_newClosePositionFeeDecayPeriod",
        type: "uint256",
      },
    ],
    name: "setClosePositionFeeDecay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0xdb9c778b",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_newOracleHeartbeatPeriod",
        type: "uint256",
      },
    ],
    name: "setOracleHeartbeatPeriod",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x024c5597",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "_newBuyingPremiumFeeMaxPercentage",
        type: "uint16",
      },
    ],
    name: "setBuyingPremiumFeeMax",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x9c631339",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "_newBuyingPremiumThreshold",
        type: "uint16",
      },
    ],
    name: "setBuyingPremiumThreshold",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0xaf2f18c5",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "_newTurbulenceStepPercentage",
        type: "uint16",
      },
    ],
    name: "setTurbulenceStep",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x34fb45f4",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "_newMaxTurbulenceFeePercentToTrim",
        type: "uint16",
      },
    ],
    name: "setMaxTurbulenceFeePercentToTrim",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x3017ac17",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "_newTurbulenceDeviationThresholdPercent",
        type: "uint16",
      },
    ],
    name: "setTurbulenceDeviationThresholdPercent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x0036c69a",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "_newTurbulenceDeviationPercentage",
        type: "uint16",
      },
    ],
    name: "setTurbulenceDeviationPercent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x7fdaf750",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "_newfundingFeeConstantRate",
        type: "uint16",
      },
    ],
    name: "setFundingFeeConstantRate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x1f3a1824",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "totalHeartbeats",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "newRounds",
        type: "uint256",
      },
      {
        internalType: "uint16",
        name: "_lastCVIValue",
        type: "uint16",
      },
      {
        internalType: "uint16",
        name: "_currCVIValue",
        type: "uint16",
      },
    ],
    name: "calculateTurbulenceIndicatorPercent",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x1ce4e15b",
  },
  {
    inputs: [
      {
        internalType: "uint168",
        name: "_tokenAmount",
        type: "uint168",
      },
      {
        internalType: "uint8",
        name: "_leverage",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "_collateralRatio",
        type: "uint256",
      },
    ],
    name: "calculateBuyingPremiumFee",
    outputs: [
      {
        internalType: "uint168",
        name: "buyingPremiumFee",
        type: "uint168",
      },
      {
        internalType: "uint16",
        name: "combinedPremiumFeePercentage",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xd8249030",
  },
  {
    inputs: [
      {
        internalType: "uint168",
        name: "_tokenAmount",
        type: "uint168",
      },
      {
        internalType: "uint8",
        name: "_leverage",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "_collateralRatio",
        type: "uint256",
      },
      {
        internalType: "uint16",
        name: "_turbulenceIndicatorPercent",
        type: "uint16",
      },
    ],
    name: "calculateBuyingPremiumFeeWithTurbulence",
    outputs: [
      {
        internalType: "uint168",
        name: "buyingPremiumFee",
        type: "uint168",
      },
      {
        internalType: "uint16",
        name: "combinedPremiumFeePercentage",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xd7e7abc1",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "period",
            type: "uint256",
          },
          {
            internalType: "uint16",
            name: "cviValue",
            type: "uint16",
          },
        ],
        internalType: "struct IFeesCalculatorV4.CVIValue[]",
        name: "_cviValues",
        type: "tuple[]",
      },
    ],
    name: "calculateSingleUnitFundingFee",
    outputs: [
      {
        internalType: "uint256",
        name: "fundingFee",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xbaed3a2e",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "creationTimestamp",
        type: "uint256",
      },
    ],
    name: "calculateClosePositionFeePercent",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x6f6bb7a7",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "calculateWithdrawFeePercent",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x81005cc3",
  },
  {
    inputs: [],
    name: "openPositionFees",
    outputs: [
      {
        internalType: "uint16",
        name: "openPositionFeePercentResult",
        type: "uint16",
      },
      {
        internalType: "uint16",
        name: "buyingPremiumFeeMaxPercentResult",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x7e3dd0f0",
  },
];

export class CVOLUSDTFeesCalculator__factory {
  static readonly abi = _abi;
  static createInterface(): CVOLUSDTFeesCalculatorInterface {
    return new utils.Interface(_abi) as CVOLUSDTFeesCalculatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CVOLUSDTFeesCalculator {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as CVOLUSDTFeesCalculator;
  }
}
