version: '3'

services:
  mysql:
    image: 'mysql:8.0.28-oracle'
    container_name: mysql-dev
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '6379:6379'
    environment:
      # root username: root
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=db1
