/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as feesCalculatorContractsSol from "./FeesCalculatorContracts.sol";
export type { feesCalculatorContractsSol };
import type * as liquiditationContractsSol from "./LiquiditationContracts.sol";
export type { liquiditationContractsSol };
import type * as platformContractsSol from "./PlatformContracts.sol";
export type { platformContractsSol };
import type * as positionRewardsContractsSol from "./PositionRewardsContracts.sol";
export type { positionRewardsContractsSol };
