/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../../../../../common";

export type PremiumParamsStruct = {
  A: BigNumberish;
  X0: BigNumberish;
  C: BigNumberish;
};

export type PremiumParamsStructOutput = [BigNumber, BigNumber, BigNumber] & {
  A: BigNumber;
  X0: BigNumber;
  C: BigNumber;
};

export interface PremiumCalculatorInterface extends utils.Interface {
  functions: {
    "calculatePremium(uint256,uint256,uint256,(int256,int256,int256),uint256,uint256,uint256)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "calculatePremium"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "calculatePremium",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      PremiumParamsStruct,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculatePremium",
    data: BytesLike
  ): Result;

  events: {};
}

export interface PremiumCalculator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PremiumCalculatorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    calculatePremium(
      lpTokensWorthAtBuyTimeUSD: BigNumberish,
      collateral: BigNumberish,
      liquidity: BigNumberish,
      premiumParams: PremiumParamsStruct,
      cvi: BigNumberish,
      premiumGrowthStart: BigNumberish,
      premiumSlope: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  calculatePremium(
    lpTokensWorthAtBuyTimeUSD: BigNumberish,
    collateral: BigNumberish,
    liquidity: BigNumberish,
    premiumParams: PremiumParamsStruct,
    cvi: BigNumberish,
    premiumGrowthStart: BigNumberish,
    premiumSlope: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    calculatePremium(
      lpTokensWorthAtBuyTimeUSD: BigNumberish,
      collateral: BigNumberish,
      liquidity: BigNumberish,
      premiumParams: PremiumParamsStruct,
      cvi: BigNumberish,
      premiumGrowthStart: BigNumberish,
      premiumSlope: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    calculatePremium(
      lpTokensWorthAtBuyTimeUSD: BigNumberish,
      collateral: BigNumberish,
      liquidity: BigNumberish,
      premiumParams: PremiumParamsStruct,
      cvi: BigNumberish,
      premiumGrowthStart: BigNumberish,
      premiumSlope: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    calculatePremium(
      lpTokensWorthAtBuyTimeUSD: BigNumberish,
      collateral: BigNumberish,
      liquidity: BigNumberish,
      premiumParams: PremiumParamsStruct,
      cvi: BigNumberish,
      premiumGrowthStart: BigNumberish,
      premiumSlope: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
