/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IKeepersFeeVault,
  IKeepersFeeVaultInterface,
} from "../../../../../../../../packages/contracts-deploy/artifacts/@coti-cvi/contracts-cvi/contracts/interfaces/IKeepersFeeVault";

const _abi = [
  {
    inputs: [],
    name: "extractUSDC",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "extractor",
        type: "address",
      },
    ],
    name: "setExtractor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IKeepersFeeVault__factory {
  static readonly abi = _abi;
  static createInterface(): IKeepersFeeVaultInterface {
    return new utils.Interface(_abi) as IKeepersFeeVaultInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKeepersFeeVault {
    return new Contract(address, _abi, signerOrProvider) as IKeepersFeeVault;
  }
}
