/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IRebaser,
  IRebaserInterface,
} from "../../../../../../../../packages/contracts-deploy/artifacts/@coti-cvi/contracts-cvi/contracts/interfaces/IRebaser";

const _abi = [
  {
    inputs: [],
    name: "rebase",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "enableWhitelist",
        type: "bool",
      },
    ],
    name: "setEnableWhitelist",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "bool",
        name: "isAllowed",
        type: "bool",
      },
    ],
    name: "setRebaserAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IUniswapV2Pair[]",
        name: "uniswapPairs",
        type: "address[]",
      },
    ],
    name: "setUniswapPairs",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "upkeepInterval",
        type: "uint32",
      },
    ],
    name: "setUpkeepInterval",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "upkeepTimeWindow",
        type: "uint32",
      },
    ],
    name: "setUpkeepTimeWindow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IVolatilityToken",
        name: "volatilityToken",
        type: "address",
      },
    ],
    name: "setVolatilityToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IRebaser__factory {
  static readonly abi = _abi;
  static createInterface(): IRebaserInterface {
    return new utils.Interface(_abi) as IRebaserInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRebaser {
    return new Contract(address, _abi, signerOrProvider) as IRebaser;
  }
}
