/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IStakingVault,
  IStakingVaultInterface,
} from "../../../../../../../../packages/contracts-deploy/artifacts/@coti-cvi/contracts-cvi/contracts/interfaces/IStakingVault";

const _abi = [
  {
    inputs: [],
    name: "extractGOVI",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "withdrawer",
        type: "address",
      },
    ],
    name: "setWithdrawer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IStakingVault__factory {
  static readonly abi = _abi;
  static createInterface(): IStakingVaultInterface {
    return new utils.Interface(_abi) as IStakingVaultInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IStakingVault {
    return new Contract(address, _abi, signerOrProvider) as IStakingVault;
  }
}
