/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { CVOLOracleETH, CVOLOracleETHInterface } from "../CVOLOracleETH";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract AggregatorV3Interface",
        name: "_cviAggregator",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "cviAggregator",
    outputs: [
      {
        internalType: "contract AggregatorV3Interface",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
  },
  {
    inputs: [
      {
        internalType: "uint80",
        name: "_roundId",
        type: "uint80",
      },
    ],
    name: "getCVIRoundData",
    outputs: [
      {
        internalType: "uint16",
        name: "cviValue",
        type: "uint16",
      },
      {
        internalType: "uint256",
        name: "cviTimestamp",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
  },
  {
    inputs: [],
    name: "getCVILatestRoundData",
    outputs: [
      {
        internalType: "uint16",
        name: "cviValue",
        type: "uint16",
      },
      {
        internalType: "uint80",
        name: "cviRoundId",
        type: "uint80",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
  },
];

export class CVOLOracleETH__factory {
  static readonly abi = _abi;
  static createInterface(): CVOLOracleETHInterface {
    return new utils.Interface(_abi) as CVOLOracleETHInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CVOLOracleETH {
    return new Contract(address, _abi, signerOrProvider) as CVOLOracleETH;
  }
}
