/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  CVOLUSDTPositionRewards,
  CVOLUSDTPositionRewardsInterface,
} from "../CVOLUSDTPositionRewards";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IERC20",
        name: "_cviToken",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
    signature: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
    signature:
      "0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0",
  },
  {
    inputs: [],
    name: "PRECISION_DECIMALS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x60ebfee6",
  },
  {
    inputs: [],
    name: "lastClaimedDay",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xae7715b1",
  },
  {
    inputs: [],
    name: "lastRewardCoefficientMax",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x49680482",
  },
  {
    inputs: [],
    name: "lastRewardCoefficientMin",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xaf972e06",
  },
  {
    inputs: [],
    name: "maxClaimPeriod",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x6ae3484e",
  },
  {
    inputs: [],
    name: "maxDailyReward",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x5fb87206",
  },
  {
    inputs: [],
    name: "maxRewardTime",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x551996f8",
  },
  {
    inputs: [],
    name: "maxSingleReward",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x9e5f4e9d",
  },
  {
    inputs: [],
    name: "minClaimPeriod",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x191d6163",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x8da5cb5b",
  },
  {
    inputs: [],
    name: "platform",
    outputs: [
      {
        internalType: "contract Platform",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x4bde38c8",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x715018a6",
  },
  {
    inputs: [],
    name: "rewardCoefficientMax",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x964fbdc7",
  },
  {
    inputs: [],
    name: "rewardCoefficientMin",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x890afa18",
  },
  {
    inputs: [],
    name: "rewardCoefficientValidTimestamp",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x74fe67ce",
  },
  {
    inputs: [],
    name: "rewarder",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xdcc3e06e",
  },
  {
    inputs: [],
    name: "todayClaimedRewards",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xc4aca6f7",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0xf2fde38b",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "unclaimedPositionUnits",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xb6929eb4",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_positionUnits",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_positionTimestamp",
        type: "uint256",
      },
    ],
    name: "calculatePositionReward",
    outputs: [
      {
        internalType: "uint256",
        name: "rewardAmount",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x5ffc5424",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_positionUnits",
        type: "uint256",
      },
    ],
    name: "reward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x21670f22",
  },
  {
    inputs: [],
    name: "claimReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0xb88a802f",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_newRewarder",
        type: "address",
      },
    ],
    name: "setRewarder",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x3a6462e4",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_newMaxDailyReward",
        type: "uint256",
      },
    ],
    name: "setMaxDailyReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x6ee30fd9",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_newMaxSingleReward",
        type: "uint256",
      },
    ],
    name: "setMaxSingleReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0xa62d5cdd",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_newRewardCoefficientMin",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_newRewardCoefficientMax",
        type: "uint256",
      },
    ],
    name: "setRewardCoefficient",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x65e8f62b",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_newMaxClaimPeriod",
        type: "uint256",
      },
    ],
    name: "setMaxClaimPeriod",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x0598e0bf",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_newMinClaimPeriod",
        type: "uint256",
      },
    ],
    name: "setMinClaimPeriod",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x5929a753",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_newMaxRewardTime",
        type: "uint256",
      },
    ],
    name: "setMaxRewardTime",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x6a538591",
  },
  {
    inputs: [
      {
        internalType: "contract Platform",
        name: "_newPlatform",
        type: "address",
      },
    ],
    name: "setPlatform",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x6945c5ea",
  },
];

export class CVOLUSDTPositionRewards__factory {
  static readonly abi = _abi;
  static createInterface(): CVOLUSDTPositionRewardsInterface {
    return new utils.Interface(_abi) as CVOLUSDTPositionRewardsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CVOLUSDTPositionRewards {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as CVOLUSDTPositionRewards;
  }
}
