/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CVIDeviationOracle } from "./CVIDeviationOracle";
export type { CVIFakeFeedOracle } from "./CVIFakeFeedOracle";
