/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CVIUSDCVolTokenRequestFulfiller } from "./CVIUSDCVolTokenRequestFulfiller";
export type { CVIUSDCVolTokenRequestFulfiller2X } from "./CVIUSDCVolTokenRequestFulfiller2X";
