/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../../../../common";

export declare namespace IVolatilityToken {
  export type RequestStruct = {
    requestType: BigNumberish;
    tokenAmount: BigNumberish;
    timeDelayRequestFeesPercent: BigNumberish;
    maxRequestFeesPercent: BigNumberish;
    owner: string;
    requestTimestamp: BigNumberish;
    targetTimestamp: BigNumberish;
    useKeepers: boolean;
    maxBuyingPremiumFeePercentage: BigNumberish;
  };

  export type RequestStructOutput = [
    number,
    BigNumber,
    number,
    number,
    string,
    number,
    number,
    boolean,
    number
  ] & {
    requestType: number;
    tokenAmount: BigNumber;
    timeDelayRequestFeesPercent: number;
    maxRequestFeesPercent: number;
    owner: string;
    requestTimestamp: number;
    targetTimestamp: number;
    useKeepers: boolean;
    maxBuyingPremiumFeePercentage: number;
  };
}

export interface CVIUSDCRequestFeesCalculator2XInterface
  extends utils.Interface {
  functions: {
    "MAX_FEE_PERCENTAGE()": FunctionFragment;
    "afterTargetMaxTime()": FunctionFragment;
    "afterTargetMaxTimePenaltyFeePercent()": FunctionFragment;
    "afterTargetMidTime()": FunctionFragment;
    "afterTargetMidTimePenaltyFeePercent()": FunctionFragment;
    "beforeTargetTimeMaxPenaltyFeePercent()": FunctionFragment;
    "calculateFindersFee(uint256)": FunctionFragment;
    "calculateKeepersFee(uint256)": FunctionFragment;
    "calculateTimeDelayFee(uint256)": FunctionFragment;
    "calculateTimePenaltyFee((uint8,uint168,uint16,uint16,address,uint32,uint32,bool,uint16))": FunctionFragment;
    "findersFeePercent()": FunctionFragment;
    "getMaxFees()": FunctionFragment;
    "isLiquidable((uint8,uint168,uint16,uint16,address,uint32,uint32,bool,uint16))": FunctionFragment;
    "keepersFeeMax()": FunctionFragment;
    "keepersFeePercent()": FunctionFragment;
    "maxTimeDelayFeePercent()": FunctionFragment;
    "maxTimeWindow()": FunctionFragment;
    "minTimeDelayFeePercent()": FunctionFragment;
    "minTimeWindow()": FunctionFragment;
    "minWaitTime()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setFindersFee(uint16)": FunctionFragment;
    "setKeepersFeeMax(uint256)": FunctionFragment;
    "setKeepersFeePercent(uint16)": FunctionFragment;
    "setMinWaitTime(uint32)": FunctionFragment;
    "setTimeDelayFeesParameters(uint16,uint16)": FunctionFragment;
    "setTimePenaltyFeeParameters(uint16,uint32,uint16,uint32,uint16)": FunctionFragment;
    "setTimeWindow(uint32,uint32)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "MAX_FEE_PERCENTAGE"
      | "afterTargetMaxTime"
      | "afterTargetMaxTimePenaltyFeePercent"
      | "afterTargetMidTime"
      | "afterTargetMidTimePenaltyFeePercent"
      | "beforeTargetTimeMaxPenaltyFeePercent"
      | "calculateFindersFee"
      | "calculateKeepersFee"
      | "calculateTimeDelayFee"
      | "calculateTimePenaltyFee"
      | "findersFeePercent"
      | "getMaxFees"
      | "isLiquidable"
      | "keepersFeeMax"
      | "keepersFeePercent"
      | "maxTimeDelayFeePercent"
      | "maxTimeWindow"
      | "minTimeDelayFeePercent"
      | "minTimeWindow"
      | "minWaitTime"
      | "owner"
      | "renounceOwnership"
      | "setFindersFee"
      | "setKeepersFeeMax"
      | "setKeepersFeePercent"
      | "setMinWaitTime"
      | "setTimeDelayFeesParameters"
      | "setTimePenaltyFeeParameters"
      | "setTimeWindow"
      | "transferOwnership"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "MAX_FEE_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "afterTargetMaxTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "afterTargetMaxTimePenaltyFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "afterTargetMidTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "afterTargetMidTimePenaltyFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "beforeTargetTimeMaxPenaltyFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateFindersFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateKeepersFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateTimeDelayFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateTimePenaltyFee",
    values: [IVolatilityToken.RequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "findersFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMaxFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isLiquidable",
    values: [IVolatilityToken.RequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "keepersFeeMax",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "keepersFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxTimeDelayFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxTimeWindow",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minTimeDelayFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minTimeWindow",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minWaitTime",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFindersFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setKeepersFeeMax",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setKeepersFeePercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinWaitTime",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTimeDelayFeesParameters",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTimePenaltyFeeParameters",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setTimeWindow",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_FEE_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "afterTargetMaxTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "afterTargetMaxTimePenaltyFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "afterTargetMidTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "afterTargetMidTimePenaltyFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beforeTargetTimeMaxPenaltyFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateFindersFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateKeepersFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateTimeDelayFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateTimePenaltyFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "findersFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMaxFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isLiquidable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "keepersFeeMax",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "keepersFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxTimeDelayFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxTimeWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minTimeDelayFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minTimeWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minWaitTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFindersFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setKeepersFeeMax",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setKeepersFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinWaitTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTimeDelayFeesParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTimePenaltyFeeParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTimeWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface CVIUSDCRequestFeesCalculator2X extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CVIUSDCRequestFeesCalculator2XInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    MAX_FEE_PERCENTAGE(overrides?: CallOverrides): Promise<[BigNumber]>;

    afterTargetMaxTime(overrides?: CallOverrides): Promise<[number]>;

    afterTargetMaxTimePenaltyFeePercent(
      overrides?: CallOverrides
    ): Promise<[number]>;

    afterTargetMidTime(overrides?: CallOverrides): Promise<[number]>;

    afterTargetMidTimePenaltyFeePercent(
      overrides?: CallOverrides
    ): Promise<[number]>;

    beforeTargetTimeMaxPenaltyFeePercent(
      overrides?: CallOverrides
    ): Promise<[number]>;

    calculateFindersFee(
      _tokensLeftAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { findersFeeAmount: BigNumber }>;

    calculateKeepersFee(
      _tokensAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { keepersFeeAmount: BigNumber }>;

    calculateTimeDelayFee(
      _timeDelay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number] & { feePercentage: number }>;

    calculateTimePenaltyFee(
      _request: IVolatilityToken.RequestStruct,
      overrides?: CallOverrides
    ): Promise<[number] & { feePercentage: number }>;

    findersFeePercent(overrides?: CallOverrides): Promise<[number]>;

    getMaxFees(
      overrides?: CallOverrides
    ): Promise<[number] & { maxFeesPercent: number }>;

    isLiquidable(
      _request: IVolatilityToken.RequestStruct,
      overrides?: CallOverrides
    ): Promise<[boolean] & { liquidable: boolean }>;

    keepersFeeMax(overrides?: CallOverrides): Promise<[BigNumber]>;

    keepersFeePercent(overrides?: CallOverrides): Promise<[number]>;

    maxTimeDelayFeePercent(overrides?: CallOverrides): Promise<[number]>;

    maxTimeWindow(overrides?: CallOverrides): Promise<[number]>;

    minTimeDelayFeePercent(overrides?: CallOverrides): Promise<[number]>;

    minTimeWindow(overrides?: CallOverrides): Promise<[number]>;

    minWaitTime(overrides?: CallOverrides): Promise<[number]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setFindersFee(
      _findersFeePercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setKeepersFeeMax(
      _keepersFeeMax: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setKeepersFeePercent(
      _keepersFeePercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMinWaitTime(
      _minWaitTime: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTimeDelayFeesParameters(
      _minTimeDelayFeePercent: BigNumberish,
      _maxTimeDelayFeePercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTimePenaltyFeeParameters(
      _beforeTargetTimeMaxPenaltyFeePercent: BigNumberish,
      _afterTargetMidTime: BigNumberish,
      _afterTargetMidTimePenaltyFeePercent: BigNumberish,
      _afterTargetMaxTime: BigNumberish,
      _afterTargetMaxTimePenaltyFeePercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTimeWindow(
      _minTimeWindow: BigNumberish,
      _maxTimeWindow: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  MAX_FEE_PERCENTAGE(overrides?: CallOverrides): Promise<BigNumber>;

  afterTargetMaxTime(overrides?: CallOverrides): Promise<number>;

  afterTargetMaxTimePenaltyFeePercent(
    overrides?: CallOverrides
  ): Promise<number>;

  afterTargetMidTime(overrides?: CallOverrides): Promise<number>;

  afterTargetMidTimePenaltyFeePercent(
    overrides?: CallOverrides
  ): Promise<number>;

  beforeTargetTimeMaxPenaltyFeePercent(
    overrides?: CallOverrides
  ): Promise<number>;

  calculateFindersFee(
    _tokensLeftAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  calculateKeepersFee(
    _tokensAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  calculateTimeDelayFee(
    _timeDelay: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  calculateTimePenaltyFee(
    _request: IVolatilityToken.RequestStruct,
    overrides?: CallOverrides
  ): Promise<number>;

  findersFeePercent(overrides?: CallOverrides): Promise<number>;

  getMaxFees(overrides?: CallOverrides): Promise<number>;

  isLiquidable(
    _request: IVolatilityToken.RequestStruct,
    overrides?: CallOverrides
  ): Promise<boolean>;

  keepersFeeMax(overrides?: CallOverrides): Promise<BigNumber>;

  keepersFeePercent(overrides?: CallOverrides): Promise<number>;

  maxTimeDelayFeePercent(overrides?: CallOverrides): Promise<number>;

  maxTimeWindow(overrides?: CallOverrides): Promise<number>;

  minTimeDelayFeePercent(overrides?: CallOverrides): Promise<number>;

  minTimeWindow(overrides?: CallOverrides): Promise<number>;

  minWaitTime(overrides?: CallOverrides): Promise<number>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setFindersFee(
    _findersFeePercent: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setKeepersFeeMax(
    _keepersFeeMax: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setKeepersFeePercent(
    _keepersFeePercent: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMinWaitTime(
    _minWaitTime: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTimeDelayFeesParameters(
    _minTimeDelayFeePercent: BigNumberish,
    _maxTimeDelayFeePercent: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTimePenaltyFeeParameters(
    _beforeTargetTimeMaxPenaltyFeePercent: BigNumberish,
    _afterTargetMidTime: BigNumberish,
    _afterTargetMidTimePenaltyFeePercent: BigNumberish,
    _afterTargetMaxTime: BigNumberish,
    _afterTargetMaxTimePenaltyFeePercent: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTimeWindow(
    _minTimeWindow: BigNumberish,
    _maxTimeWindow: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    MAX_FEE_PERCENTAGE(overrides?: CallOverrides): Promise<BigNumber>;

    afterTargetMaxTime(overrides?: CallOverrides): Promise<number>;

    afterTargetMaxTimePenaltyFeePercent(
      overrides?: CallOverrides
    ): Promise<number>;

    afterTargetMidTime(overrides?: CallOverrides): Promise<number>;

    afterTargetMidTimePenaltyFeePercent(
      overrides?: CallOverrides
    ): Promise<number>;

    beforeTargetTimeMaxPenaltyFeePercent(
      overrides?: CallOverrides
    ): Promise<number>;

    calculateFindersFee(
      _tokensLeftAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateKeepersFee(
      _tokensAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateTimeDelayFee(
      _timeDelay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;

    calculateTimePenaltyFee(
      _request: IVolatilityToken.RequestStruct,
      overrides?: CallOverrides
    ): Promise<number>;

    findersFeePercent(overrides?: CallOverrides): Promise<number>;

    getMaxFees(overrides?: CallOverrides): Promise<number>;

    isLiquidable(
      _request: IVolatilityToken.RequestStruct,
      overrides?: CallOverrides
    ): Promise<boolean>;

    keepersFeeMax(overrides?: CallOverrides): Promise<BigNumber>;

    keepersFeePercent(overrides?: CallOverrides): Promise<number>;

    maxTimeDelayFeePercent(overrides?: CallOverrides): Promise<number>;

    maxTimeWindow(overrides?: CallOverrides): Promise<number>;

    minTimeDelayFeePercent(overrides?: CallOverrides): Promise<number>;

    minTimeWindow(overrides?: CallOverrides): Promise<number>;

    minWaitTime(overrides?: CallOverrides): Promise<number>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setFindersFee(
      _findersFeePercent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setKeepersFeeMax(
      _keepersFeeMax: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setKeepersFeePercent(
      _keepersFeePercent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMinWaitTime(
      _minWaitTime: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setTimeDelayFeesParameters(
      _minTimeDelayFeePercent: BigNumberish,
      _maxTimeDelayFeePercent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setTimePenaltyFeeParameters(
      _beforeTargetTimeMaxPenaltyFeePercent: BigNumberish,
      _afterTargetMidTime: BigNumberish,
      _afterTargetMidTimePenaltyFeePercent: BigNumberish,
      _afterTargetMaxTime: BigNumberish,
      _afterTargetMaxTimePenaltyFeePercent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setTimeWindow(
      _minTimeWindow: BigNumberish,
      _maxTimeWindow: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    MAX_FEE_PERCENTAGE(overrides?: CallOverrides): Promise<BigNumber>;

    afterTargetMaxTime(overrides?: CallOverrides): Promise<BigNumber>;

    afterTargetMaxTimePenaltyFeePercent(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    afterTargetMidTime(overrides?: CallOverrides): Promise<BigNumber>;

    afterTargetMidTimePenaltyFeePercent(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    beforeTargetTimeMaxPenaltyFeePercent(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateFindersFee(
      _tokensLeftAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateKeepersFee(
      _tokensAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateTimeDelayFee(
      _timeDelay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateTimePenaltyFee(
      _request: IVolatilityToken.RequestStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    findersFeePercent(overrides?: CallOverrides): Promise<BigNumber>;

    getMaxFees(overrides?: CallOverrides): Promise<BigNumber>;

    isLiquidable(
      _request: IVolatilityToken.RequestStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    keepersFeeMax(overrides?: CallOverrides): Promise<BigNumber>;

    keepersFeePercent(overrides?: CallOverrides): Promise<BigNumber>;

    maxTimeDelayFeePercent(overrides?: CallOverrides): Promise<BigNumber>;

    maxTimeWindow(overrides?: CallOverrides): Promise<BigNumber>;

    minTimeDelayFeePercent(overrides?: CallOverrides): Promise<BigNumber>;

    minTimeWindow(overrides?: CallOverrides): Promise<BigNumber>;

    minWaitTime(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setFindersFee(
      _findersFeePercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setKeepersFeeMax(
      _keepersFeeMax: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setKeepersFeePercent(
      _keepersFeePercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMinWaitTime(
      _minWaitTime: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTimeDelayFeesParameters(
      _minTimeDelayFeePercent: BigNumberish,
      _maxTimeDelayFeePercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTimePenaltyFeeParameters(
      _beforeTargetTimeMaxPenaltyFeePercent: BigNumberish,
      _afterTargetMidTime: BigNumberish,
      _afterTargetMidTimePenaltyFeePercent: BigNumberish,
      _afterTargetMaxTime: BigNumberish,
      _afterTargetMaxTimePenaltyFeePercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTimeWindow(
      _minTimeWindow: BigNumberish,
      _maxTimeWindow: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MAX_FEE_PERCENTAGE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    afterTargetMaxTime(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    afterTargetMaxTimePenaltyFeePercent(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    afterTargetMidTime(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    afterTargetMidTimePenaltyFeePercent(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    beforeTargetTimeMaxPenaltyFeePercent(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateFindersFee(
      _tokensLeftAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateKeepersFee(
      _tokensAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateTimeDelayFee(
      _timeDelay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateTimePenaltyFee(
      _request: IVolatilityToken.RequestStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    findersFeePercent(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMaxFees(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isLiquidable(
      _request: IVolatilityToken.RequestStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    keepersFeeMax(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    keepersFeePercent(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maxTimeDelayFeePercent(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxTimeWindow(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    minTimeDelayFeePercent(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    minTimeWindow(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    minWaitTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setFindersFee(
      _findersFeePercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setKeepersFeeMax(
      _keepersFeeMax: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setKeepersFeePercent(
      _keepersFeePercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMinWaitTime(
      _minWaitTime: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTimeDelayFeesParameters(
      _minTimeDelayFeePercent: BigNumberish,
      _maxTimeDelayFeePercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTimePenaltyFeeParameters(
      _beforeTargetTimeMaxPenaltyFeePercent: BigNumberish,
      _afterTargetMidTime: BigNumberish,
      _afterTargetMidTimePenaltyFeePercent: BigNumberish,
      _afterTargetMaxTime: BigNumberish,
      _afterTargetMaxTimePenaltyFeePercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTimeWindow(
      _minTimeWindow: BigNumberish,
      _maxTimeWindow: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
