/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface FeesModelInterface extends utils.Interface {
  contractName: "FeesModel";
  functions: {
    "maxOracleValuesUsed()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateSnapshots()": FunctionFragment;
    "setCVIOracle(address)": FunctionFragment;
    "setFeesCalculator(address)": FunctionFragment;
    "setLatestOracleRoundId(uint80)": FunctionFragment;
    "setMaxOracleValuesUsed(uint80)": FunctionFragment;
    "calculateFundingFees(uint256,uint256,uint256)": FunctionFragment;
    "calculateFundingFeesAddendum(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "maxOracleValuesUsed",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSnapshots",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCVIOracle",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeesCalculator",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setLatestOracleRoundId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxOracleValuesUsed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateFundingFees",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateFundingFeesAddendum",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "maxOracleValuesUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSnapshots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCVIOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeesCalculator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLatestOracleRoundId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxOracleValuesUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateFundingFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateFundingFeesAddendum",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface FeesModel extends BaseContract {
  contractName: "FeesModel";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FeesModelInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    maxOracleValuesUsed(overrides?: CallOverrides): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateSnapshots(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setCVIOracle(
      _newOracle: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setFeesCalculator(
      _newCalculator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setLatestOracleRoundId(
      _newOracleRoundId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMaxOracleValuesUsed(
      _newMaxOracleValuesUsed: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "calculateFundingFees(uint256,uint256,uint256)"(
      startTime: BigNumberish,
      endTime: BigNumberish,
      positionUnitsAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "calculateFundingFees(uint256,uint256)"(
      startTime: BigNumberish,
      positionUnitsAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    calculateFundingFeesAddendum(
      positionUnitsAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  maxOracleValuesUsed(overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateSnapshots(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setCVIOracle(
    _newOracle: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setFeesCalculator(
    _newCalculator: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setLatestOracleRoundId(
    _newOracleRoundId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMaxOracleValuesUsed(
    _newMaxOracleValuesUsed: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "calculateFundingFees(uint256,uint256,uint256)"(
    startTime: BigNumberish,
    endTime: BigNumberish,
    positionUnitsAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "calculateFundingFees(uint256,uint256)"(
    startTime: BigNumberish,
    positionUnitsAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  calculateFundingFeesAddendum(
    positionUnitsAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    maxOracleValuesUsed(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateSnapshots(overrides?: CallOverrides): Promise<BigNumber>;

    setCVIOracle(_newOracle: string, overrides?: CallOverrides): Promise<void>;

    setFeesCalculator(
      _newCalculator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setLatestOracleRoundId(
      _newOracleRoundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMaxOracleValuesUsed(
      _newMaxOracleValuesUsed: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "calculateFundingFees(uint256,uint256,uint256)"(
      startTime: BigNumberish,
      endTime: BigNumberish,
      positionUnitsAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "calculateFundingFees(uint256,uint256)"(
      startTime: BigNumberish,
      positionUnitsAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateFundingFeesAddendum(
      positionUnitsAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    maxOracleValuesUsed(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateSnapshots(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setCVIOracle(
      _newOracle: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setFeesCalculator(
      _newCalculator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setLatestOracleRoundId(
      _newOracleRoundId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMaxOracleValuesUsed(
      _newMaxOracleValuesUsed: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "calculateFundingFees(uint256,uint256,uint256)"(
      startTime: BigNumberish,
      endTime: BigNumberish,
      positionUnitsAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "calculateFundingFees(uint256,uint256)"(
      startTime: BigNumberish,
      positionUnitsAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateFundingFeesAddendum(
      positionUnitsAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    maxOracleValuesUsed(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateSnapshots(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setCVIOracle(
      _newOracle: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setFeesCalculator(
      _newCalculator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setLatestOracleRoundId(
      _newOracleRoundId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMaxOracleValuesUsed(
      _newMaxOracleValuesUsed: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "calculateFundingFees(uint256,uint256,uint256)"(
      startTime: BigNumberish,
      endTime: BigNumberish,
      positionUnitsAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "calculateFundingFees(uint256,uint256)"(
      startTime: BigNumberish,
      positionUnitsAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateFundingFeesAddendum(
      positionUnitsAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
