apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: '"PUT, GET, POST, OPTIONS"'
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/enable-cors: '"true"'
    cert-manager.io/acme-challenge-type: dns01
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
  labels:
    app.kubernetes.io/managed-by: Helm
    app: cvi-monitor-ethereum-goerli
  name: cvi-monitor-ethereum-goerli-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: cvi-monitor-ethereum-goerli.cvi-team.com
    http:
      paths:
      - backend:
          service:
            name: cvi-monitor-ethereum-goerli 
            port: 
              number: 80
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - cvi-monitor-ethereum-goerli.cvi-team.com
    secretName: backend-cert-cvi-monitor-ethereum-goerli
