apiVersion: v1
kind: Service
metadata:
  annotations:
      meta.helm.sh/release-name: {{ .Release.Name }}
      meta.helm.sh/release-namespace: {{ .Release.Namespace }}
      field.cattle.io/targetWorkloadIds: '["statefulset:default:cvi-monitor-ethereum-goerli"]'
      workload.cattle.io/targetWorkloadIdNoop: "true"
      workload.cattle.io/workloadPortBased: "true"
  labels:
    app.kubernetes.io/managed-by: Helm
    cattle.io/creator: norman
    app: cvi-monitor-ethereum-goerli
  name: cvi-monitor-ethereum-goerli
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: tcpport01
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: statefulSet-default-cvi-monitor-ethereum-goerli
  sessionAffinity: None
  type: ClusterIP
