apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: '"PUT, GET, POST, OPTIONS"'
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/enable-cors: '"true"'
    cert-manager.io/acme-challenge-type: dns01
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/websocket-services: hardhat-arbitrum
    nginx.org/websocket-services: hardhat-arbitrum
  labels:
    app.kubernetes.io/managed-by: Helm
    app: hardhat-arbitrum
  name: hardhat-arbitrum-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: hardhat-arbitrum.cvi-team.com
    http:
      paths:
      - backend:
          service:
            name: hardhat-arbitrum
            port: 
              number: 80
        pathType: ImplementationSpecific
  - host: hardhat-arbitrum-deployments-file.cvi-team.com
    http:
      paths:
      - backend:
          service:
            name: hardhat-arbitrum
            port: 
              number: 81
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - hardhat-arbitrum.cvi-team.com
    - hardhat-arbitrum-deployments-file.cvi-team.com
    secretName: backend-cert-hardhat-arbitrum
