apiVersion: v1
kind: Service
metadata:
  annotations:
      meta.helm.sh/release-name: {{ .Release.Name }}
      meta.helm.sh/release-namespace: {{ .Release.Namespace }}
      field.cattle.io/targetWorkloadIds: '["deployment:default:hardhat-arbitrum"]'
      workload.cattle.io/targetWorkloadIdNoop: "true"
      workload.cattle.io/workloadPortBased: "true"
  labels:
    app.kubernetes.io/managed-by: Helm
    cattle.io/creator: norman
    app: hardhat-arbitrum
  name: hardhat-arbitrum
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: tcpport01
      port: 80
      protocol: TCP
      targetPort: 9545
    - name: tcpport02
      port: 81
      protocol: TCP
      targetPort: 6999

  selector:
    workload.user.cattle.io/workloadselector: deployment-default-hardhat-arbitrum
  sessionAffinity: None
  type: ClusterIP
