/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../../../../../common";

export interface IRebaserInterface extends utils.Interface {
  functions: {
    "rebase()": FunctionFragment;
    "setEnableWhitelist(bool)": FunctionFragment;
    "setRebaserAddress(address,bool)": FunctionFragment;
    "setUniswapPairs(address[])": FunctionFragment;
    "setUpkeepInterval(uint32)": FunctionFragment;
    "setUpkeepTimeWindow(uint32)": FunctionFragment;
    "setVolatilityToken(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "rebase"
      | "setEnableWhitelist"
      | "setRebaserAddress"
      | "setUniswapPairs"
      | "setUpkeepInterval"
      | "setUpkeepTimeWindow"
      | "setVolatilityToken"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "rebase", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setEnableWhitelist",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setRebaserAddress",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setUniswapPairs",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setUpkeepInterval",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setUpkeepTimeWindow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVolatilityToken",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "rebase", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setEnableWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRebaserAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUniswapPairs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUpkeepInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUpkeepTimeWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVolatilityToken",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IRebaser extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IRebaserInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    rebase(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setEnableWhitelist(
      enableWhitelist: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setRebaserAddress(
      user: string,
      isAllowed: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setUniswapPairs(
      uniswapPairs: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setUpkeepInterval(
      upkeepInterval: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setUpkeepTimeWindow(
      upkeepTimeWindow: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setVolatilityToken(
      volatilityToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  rebase(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setEnableWhitelist(
    enableWhitelist: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setRebaserAddress(
    user: string,
    isAllowed: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setUniswapPairs(
    uniswapPairs: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setUpkeepInterval(
    upkeepInterval: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setUpkeepTimeWindow(
    upkeepTimeWindow: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setVolatilityToken(
    volatilityToken: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    rebase(overrides?: CallOverrides): Promise<void>;

    setEnableWhitelist(
      enableWhitelist: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setRebaserAddress(
      user: string,
      isAllowed: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setUniswapPairs(
      uniswapPairs: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    setUpkeepInterval(
      upkeepInterval: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setUpkeepTimeWindow(
      upkeepTimeWindow: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setVolatilityToken(
      volatilityToken: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    rebase(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setEnableWhitelist(
      enableWhitelist: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setRebaserAddress(
      user: string,
      isAllowed: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setUniswapPairs(
      uniswapPairs: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setUpkeepInterval(
      upkeepInterval: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setUpkeepTimeWindow(
      upkeepTimeWindow: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setVolatilityToken(
      volatilityToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    rebase(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setEnableWhitelist(
      enableWhitelist: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setRebaserAddress(
      user: string,
      isAllowed: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setUniswapPairs(
      uniswapPairs: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setUpkeepInterval(
      upkeepInterval: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setUpkeepTimeWindow(
      upkeepTimeWindow: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setVolatilityToken(
      volatilityToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
