apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    app: il-monitor-polygon-staging
  name: il-monitor-polygon-staging
  namespace: default
spec:
  endpoints:
  - interval: 1m
    path: /metrics
    port: tcpport01
    targetPort: 80
  jobLabel: il-monitor-polygon-staging
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: il-monitor-polygon-staging