// eslint-disable-next-line @typescript-eslint/no-var-requires
const defaultTheme = require('tailwindcss/defaultTheme')

/** @type {import('tailwindcss/tailwind-config').TailwindConfig} */
module.exports = {
  mode: 'jit',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    screens: {
      xs: '360px',
      xm: '375px',
      stiny: '460px',
      tiny: '517px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
      '3xl': '1571px',
    },
    extend: {
      padding: {
        3.8: '0.8133rem',
        5.5: '1rem',
        7.5: '1.844rem',
        15: '3.669rem',
      },
      inset: {
        '3px': '3px',
      },
      width: {
        38: '9.5rem',
        41: '10.25rem',
        43: '11.75rem',
        45: '12.375rem',
        60: '15.65rem',
        70: '19.5rem',
        89: '22.25rem',
        100: '25rem',
        102: '25.625rem',
        105: '25.75rem',
        110: '31rem',
        118: '34rem',
        124: '37.5rem',
        198: '48rem',
        206: '50rem',
      },
      height: {
        17: '4.5rem',
        100: '25rem',
        102: '25.625rem',
        105: '25.75rem',
        110: '31rem',
        118: '34rem',
        124: '37.5rem',
        198: '48rem',
        206: '50rem',
        210: '60rem',
      },
      colors: {
        ...defaultTheme.colors,
        custom: {
          'connect-bg': () => `var(--color-custom-connect-bg)`,
          'connect-bg-opacity-20': () => `var(--color-custom-connect-bg-opacity-20)`,
          'network-border': () => `var(--color-custom-network-border)`,
          'network-border-opacity-20': () => `var(--color-custom-network-border-opacity-20)`,
          100: () => `var(--color-custom-100)`,
          200: () => `var(--color-custom-200)`,
          '200-opacity-20': () => `var(--color-custom-200-opacity-20)`,
          300: () => `var(--color-custom-300)`,
          btc: () => `var(--color-custom-btc)`,
          eth: () => `var(--color-custom-eth)`,
          '300-opacity-20': () => `var(--color-custom-300-opacity-20)`,
          '300-opacity-70': () => `var(--color-custom-300-opacity-70)`,
          400: () => `var(--color-custom-400)`,
          500: () => `var(--color-custom-500)`,
          '500-opacity-63': () => `var(--color-custom-500-opacity-63)`,
          600: () => `var(--color-custom-600)`,
          'nav-bg': () => `var(--color-custom-nav-bg)`,
          'win-bg': () => `var(--color-custom-window-bg)`,
          'win-bg-opacity-20': () => `var(--color-custom-window-bg-opacity-20)`,
          'container-bg': () => `var(--color-custom-container-bg)`,
          'textlink-hover': () => `var(--color-custom-textlink-hover)`,
          'slippage-bg': () => `var(--color-custom-slippage-bg)`,
          'slippage-input-bg': () => `var(--color-custom-slippage-input-bg)`,
          'cancel-bg': () => `var(--color-custom-cancel-bg)`,
          'cancel-bg-opacity-25': () => `var(--color-custom-cancel-bg-opacity-25)`,
          'len-data-history-bg': () => `var(--color-custom-len-data-history-bg)`,
          'cancel-disabled-bg-opacity-20': () => `var(--color-custom-cancel-disabled-bg-opacity-20)`,
          'community-hover': () => `var(--color-custom-community-hover)`,
          'community-click': () => `var(--color-custom-community-click)`,
          community: () => `var(--color-custom-community)`,
          'big-theta_1x': () => `var(--color-custom-big-theta_1x)`,
          'big-theta_2x': () => `var(--color-custom-big-theta_2x)`,
        },
        dark: {
          100: '#182f5d',
          200: '#0f122d',
          250: '#212338',
          300: '#222540',
          350: '#2b2f4c',
          400: '#2f3250',
          450: '#0010ff',
          600: '#1b1d38',
          650: '#1c1e32',
          700: '#0f112d',
          800: '#03070f',
        },
        common: {
          xsGray: '#c4c7e0',
          lightGray: '#b2bfce',
          lightOrange: '#ffbb59',
          orange: '#fea716',
          turquoise: '#2bdec1',
          lightRed: '#f96a9a',
          blue: '#2b387c',
          lightGreen: '#2bbede',
          cancel: '#2f3250',
          red: '#bb1e52',
          blueSky: '#007acb', //#2b307f#4c57ff
          lightPink: '#8247e5',
          armadilloBg: '#0f101f',
        },
        modal: { closeBtn: '#264fa1' },
        table: { firstTrOdd: '#1a2243', spinner: '#10bfa0' },
        alerts: { background: '#141741' },
        progressBar: { background: '#2b2f4c' },
      },
      fontFamily: {
        sans: ['OpenSans', ...defaultTheme.fontFamily.sans],
        roboto: ['Roboto', ...defaultTheme.fontFamily.sans],
      },
      fontSize: {
        xt: '.575rem',
        tiny: '.675rem',
        11: '0.688rem',
        xs: '.75rem',
        sm: '.875rem',
        md: '.938rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.063rem',
        '5xl': '2.25rem',
        '6xl': '3rem',
        '7xl': '4rem',
        '8xl': '5rem',
      },
    },
  },
  variants: {
    extend: {},
  },
}
