/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stakingContractsSol from "./StakingContracts.sol";
export type { stakingContractsSol };
import type * as stakingRewardsSol from "./StakingRewards.sol";
export type { stakingRewardsSol };
export type { FeesCollector } from "./FeesCollector";
export type { Staking } from "./Staking";
export type { StakingVault } from "./StakingVault";
export type { Treasury } from "./Treasury";
