/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contractsCvi from "./contracts-cvi";
export type { contractsCvi };
import type * as contractsIl from "./contracts-il";
export type { contractsIl };
import type * as contractsStaking from "./contracts-staking";
export type { contractsStaking };
