apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: statefulSet-default-il-monitor-arbitrum-mainnet
    app: il-monitor-arbitrum-mainnet
  name: il-monitor-arbitrum-mainnet
  namespace: {{ .Release.Namespace }}
spec:
  podManagementPolicy: OrderedReady
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: statefulSet-default-il-monitor-arbitrum-mainnet
  serviceName: il-monitor-arbitrum-mainnet
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: statefulSet-default-il-monitor-arbitrum-mainnet
    spec:
      containers:
        - args:
            - node
            - packages/il-monitor/dist/index.js
          env:
          - name: APP_ENV
            value: 'k8s'
          - name: CHAIN_ID
            value: '42161'
          - name: PERFORM_UPKEEP
            value: 'false'
          image: {{ .Values.global.backend_image }}
          imagePullPolicy: Always
          name: il-monitor-arbitrum-mainnet
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readiness
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 2
          ports:
            - containerPort: 80
              name: tcpport01
              protocol: TCP
          resources:
            requests: # min
              cpu: 250m
              memory: 1000Mi
            limits: # max
              cpu: 250m
              memory: 1000Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: dockerhub-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
