/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CVIUSDCThetaVault__factory } from "./CVIUSDCThetaVault__factory";
export { CVIUSDCThetaVault2X__factory } from "./CVIUSDCThetaVault2X__factory";
